apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  labels:
    app: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
        - name: log-generator
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              i=0
              while true; do
                echo "{\"level\":\"INFO\",\"message\":\"EFK test log\",\"counter\":$i}"
                i=$((i+1))
                sleep 5
              done
